backend:
  name: github
  repo: scwambach/wambachdev # Path to your GitHub repository
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "/source/images/uploads"
public_folder: "/images/uploads"

collections:

  ###########################################
  ############## SITE SETTINGS ##############
  ###########################################

  - label: "Site Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Global Settings"
        name: "global"
        file: "data/site_settings.yml"
        fields:
          - {label: Favicon, name: favicon, widget: image}
          - {label: Footer Copy, name: footer_copy, widget: string}
          - label: "Socials"
            name: "socials"
            widget: "list"
            fields:
              - label: Icon
                name: icon
                widget: string
              - label: URL
                name: url
                widget: string
      - label: "Projects"
        name: "projects"
        file: "data/projects.yml"
        fields:
          - label: "Project Items"
            name: "project_items"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
