backend:
  name: github
  repo: scwambach/wambachdev # Path to your GitHub repository
  branch: master # Branch to update (optional; defaults to master)

# publish_mode: editorial_workflow

media_folder: '/source/images/uploads'
public_folder: '/images/uploads'

collections:

  - label: 'Projects'
    name: 'projects'
    format: 'yml'
    folder: 'data/project_items'
    create: true
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'URL', name: 'url', widget: 'string'}
      - {label: 'CMS', name: 'cms', widget: 'string'}
      - {label: 'Role', name: 'role', widget: 'string'}
      - label: 'Collaborators'
        name: 'collaborators'
        widget: 'list'
        fields:
          - {label: 'Collaborator', name: 'collaborator', widget: 'string'}
      - label: 'Screens'
        name: 'screens'
        widget: 'list'
        fields:
          - label: 'image'
            name: 'image'
            widget: 'image'

  ###########################################
  ############## SITE SETTINGS ##############
  ###########################################

  - label: 'Site Settings'
    name: 'settings'
    editor:
      preview: false
    files:
      - label: 'Global Settings'
        name: 'global'
        file: 'data/site_settings.yml'
        fields:
          - {label: Site Title, name: site_title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: Favicon, name: favicon, widget: image}
          - {label: Footer Copy, name: footer_copy, widget: string}
          - label: 'Socials'
            name: 'socials'
            widget: 'list'
            fields:
              - label: Icon
                name: icon
                widget: string
              - label: URL
                name: url
                widget: string
      - label: 'Project Order'
        name: 'project_order'
        file: 'data/projects_order.yml'
        fields:
          - label: 'Ordered Items'
            name: 'order_items'
            widget: 'list'
            fields:
              - label: "Project"
                name: "project"
                widget: "relation"
                collection: "projects"
                searchFields: ["title"]
                valueField: "title"
                displayFields: ["title"]
